version: '3'
networks:
  main:
services:
  mw:
    image: alankang/mw-docker
    networks:
      main:
        aliases:
          - mw
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - data-mw:/data:rw
      - ${PWD}/custom:/custom:ro
    environment:
      - MEDIAWIKI_SITE_SERVER=${MEDIAWIKI_SITE_SERVER}
      - MEDIAWIKI_SITE_NAME=${MEDIAWIKI_SITE_NAME}
      - MEDIAWIKI_SITE_LANG=${MEDIAWIKI_SITE_LANG}
      - MEDIAWIKI_ADMIN_USER=${MEDIAWIKI_ADMIN_USER}
      - MEDIAWIKI_ADMIN_PASS=${MEDIAWIKI_ADMIN_PASS}
      - MEDIAWIKI_ADMIN_EMAIL=${MEDIAWIKI_ADMIN_EMAIL}
      - MEDIAWIKI_DB_USER=${MEDIAWIKI_DB_USER}
      - MEDIAWIKI_DB_PASSWORD=${MEDIAWIKI_DB_PASSWORD}
      - MEDIAWIKI_PROTOCOL=${MEDIAWIKI_PROTOCOL}
  restbase:
    image: alankang/mw-node-docker
    networks:
      main:
        aliases:
          - restbase
    environment:
      - MEDIAWIKI_SITE_SERVER=${MEDIAWIKI_SITE_SERVER}
      - MEDIAWIKI_PROTOCOL=${MEDIAWIKI_PROTOCOL}
  mysql:
    image: mariadb
    networks:
      main:
        aliases:
          - mysql
    volumes:
      - data-mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=${MEDIAWIKI_DB_PASSWORD}

volumes:
  data-mw:
  data-mysql:
